/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.raven.form;

import Services.StatsticService;
import com.raven.model.Model_Card;
import java.awt.BorderLayout;
import java.text.SimpleDateFormat;
import java.util.Date;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.CategoryDataset;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author RAVEN
 */
public final class Form_ThongKe extends javax.swing.JPanel {

    /**
     * Creates new form Form_1
     */
    public Form_ThongKe() {

        initComponents();
        this.LoadStatistics();

    }

    private void initializeChart(String from, String to) {
        Dashboard_Bot.removeAll();

        JFreeChart chart = createChart(from, to);
        ChartPanel chartPanel = new ChartPanel(chart);
        chartPanel.setPreferredSize(new java.awt.Dimension(1000, 600));

        Dashboard_Bot.setLayout(new BorderLayout());
        Dashboard_Bot.add(chartPanel, BorderLayout.CENTER);

        Dashboard_Bot.revalidate();
        Dashboard_Bot.repaint();
    }

    public JFreeChart createChart(String from, String to) {
        return ChartFactory.createBarChart(
                "Biểu đồ thống kê doanh thu",
                "Tháng", "Doanh thu",
                createDataset(from, to), PlotOrientation.VERTICAL, false, false, false);
    }

    private CategoryDataset createDataset(String from, String to) {
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        StatsticService service = new StatsticService();
        System.out.println("com.raven.form.Form_ThongKe.createDataset()1");
        service.GetDataChart(from, to).forEach(data -> {
            System.out.println("com.raven.form.Form_ThongKe.createDataset()2");
            System.out.println(data.getMonth());
            System.out.println(data.getTotal());
            dataset.addValue(data.getTotal(), "Doanh thu", "Tháng " + String.valueOf(data.getMonth()));
        });
        System.out.println("com.raven.form.Form_ThongKe.createDataset()3");
        return dataset;
    }

    private void LoadStatistics() {
        StatsticService statsticService = new StatsticService();
        card1.setData(new Model_Card("Điểm cao nhất", String.valueOf(statsticService.GetData().getMaxPoints())));
        card2.setData(new Model_Card("Tổng số khách hàng thân thiết", String.valueOf(statsticService.GetData().getTotalLoyaltyCustomers())));
        card3.setData(new Model_Card("Tổng doanh thu", String.valueOf(statsticService.GetData().getTotalRevenue())));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Dashboard_Top = new javax.swing.JPanel();
        card2 = new com.raven.component.Card();
        card3 = new com.raven.component.Card();
        card1 = new com.raven.component.Card();
        OptionDashboard = new javax.swing.JPanel();
        DateFrom = new com.toedter.calendar.JDateChooser();
        DateTo = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn_Statstic = new javax.swing.JButton();
        Dashboard_Bot = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));

        Dashboard_Top.setBackground(new java.awt.Color(255, 255, 255));
        Dashboard_Top.setLayout(new java.awt.GridLayout(1, 0, 10, 0));
        Dashboard_Top.add(card2);
        Dashboard_Top.add(card3);
        Dashboard_Top.add(card1);

        DateFrom.setDateFormatString("yyyy-MM-dd");

        DateTo.setDateFormatString("yyyy-MM-dd");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("From");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("To");

        btn_Statstic.setText("Thống kê");
        btn_Statstic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_StatsticActionPerformed(evt);
            }
        });

        Dashboard_Bot.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout Dashboard_BotLayout = new javax.swing.GroupLayout(Dashboard_Bot);
        Dashboard_Bot.setLayout(Dashboard_BotLayout);
        Dashboard_BotLayout.setHorizontalGroup(
            Dashboard_BotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        Dashboard_BotLayout.setVerticalGroup(
            Dashboard_BotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 435, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout OptionDashboardLayout = new javax.swing.GroupLayout(OptionDashboard);
        OptionDashboard.setLayout(OptionDashboardLayout);
        OptionDashboardLayout.setHorizontalGroup(
            OptionDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, OptionDashboardLayout.createSequentialGroup()
                .addContainerGap(189, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DateFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DateTo, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_Statstic)
                .addGap(30, 30, 30))
            .addComponent(Dashboard_Bot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        OptionDashboardLayout.setVerticalGroup(
            OptionDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, OptionDashboardLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(OptionDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_Statstic, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, OptionDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(DateTo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(DateFrom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Dashboard_Bot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Dashboard_Top, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 838, Short.MAX_VALUE)
                    .addComponent(OptionDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Dashboard_Top, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(OptionDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_StatsticActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_StatsticActionPerformed
        // TODO add your handling code here:
        Date selectedDateFrom = DateFrom.getDate();
        Date selectedDateTo = DateTo.getDate();

        if (selectedDateFrom != null && selectedDateTo != null) {
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            String formattedDateFrom = dateFormat.format(selectedDateFrom);
            String formattedDateTo = dateFormat.format(selectedDateTo);
            this.initializeChart(formattedDateFrom, formattedDateTo);

        }
    }//GEN-LAST:event_btn_StatsticActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Dashboard_Bot;
    private javax.swing.JPanel Dashboard_Top;
    private com.toedter.calendar.JDateChooser DateFrom;
    private com.toedter.calendar.JDateChooser DateTo;
    private javax.swing.JPanel OptionDashboard;
    private javax.swing.JButton btn_Statstic;
    private com.raven.component.Card card1;
    private com.raven.component.Card card2;
    private com.raven.component.Card card3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
